-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 11:20:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `carga_horaria` VARCHAR(60) NULL,
  `preco` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `formacao` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_turma` VARCHAR(60) NULL,
  `inicio` DATE NULL,
  `fim` DATE NULL,
  `cursos_id` INT NOT NULL,
  `professores_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cursos_id`, `professores_id`),
  INDEX `fk_turmas_cursos_idx` (`cursos_id` ASC) VISIBLE,
  INDEX `fk_turmas_professores1_idx` (`professores_id` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_cursos`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_professores1`
    FOREIGN KEY (`professores_id`)
    REFERENCES `mydb`.`professores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `cpf` VARCHAR(14) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matriculas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(60) NULL,
  `alunos_id` INT NOT NULL,
  `turmas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `alunos_id`, `turmas_id`),
  INDEX `fk_matriculas_alunos1_idx` (`alunos_id` ASC) VISIBLE,
  INDEX `fk_matriculas_turmas1_idx` (`turmas_id` ASC) VISIBLE,
  CONSTRAINT `fk_matriculas_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `mydb`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_turmas1`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `mydb`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
